export { default as Main } from './Main';
export { default as Category } from './Category';
export { default as LocationEdit } from './LocationEdit';
export { default as Menu } from './Menu';
export { default as NewProduct } from './NewProduct';
export { default as ProductDetail } from './ProductDetail';
export { default as SignIn } from './SignIn';
export { default as SignUp } from './SignUp';
export { default as NotFound } from './NotFound';
